Upgrading Angular from 15 to 16. That allows upgrading TS from 4.9 to 5.1. That allows upgrading moduleResolution from node10 to bundler. That clears the compiler error TS5107: Option 'moduleResolution=node10' is deprecated and will stop functioning in TypeScript 7.0.